/** DI token — inject with `@Inject(PAYMENT_PROVIDER)`. */
export const PAYMENT_PROVIDER = 'PAYMENT_PROVIDER';

export interface InitiateCheckoutInput {
  /** The provider's own idempotency/tracking key — generated by us before
   * calling the provider, so we can create a matching PaymentIntent row
   * before the customer is ever redirected. */
  reference: string;
  /** Whole currency units (Naira) — the provider adapter is responsible
   * for converting to whatever minor unit the real API expects. */
  amount: number;
  currency: string;
  customerEmail: string;
  /** Where the provider should send the browser back to once the
   * customer finishes (or abandons) the hosted checkout page. */
  callbackUrl: string;
}

export interface InitiateCheckoutResult {
  /** URL to redirect the customer's browser to. */
  authorizationUrl: string;
  reference: string;
}

export interface VerifyCheckoutResult {
  reference: string;
  success: boolean;
  /** Whole currency units, as confirmed by the provider — compared against
   * the PaymentIntent's own recorded amount before trusting it. */
  amount: number;
  currency: string;
}

/**
 * Vendor-agnostic seam for online checkout, mirroring how
 * FlightProviderPort decouples Duffel from booking and
 * NotificationProviderPort decouples SMTP from sending. A real gateway
 * (Paystack, Flutterwave, Stripe, ...) implements this the same way, so
 * swapping providers is a DI binding change, not a rewrite of
 * PaymentsService or its controllers.
 */
export interface PaymentProviderPort {
  initiateCheckout(
    input: InitiateCheckoutInput,
  ): Promise<InitiateCheckoutResult>;
  verifyCheckout(reference: string): Promise<VerifyCheckoutResult>;
}
