import type { NavLink } from '@/components/AppShell';
import { assignGroups } from './nav-groups';

const ADMIN_LINKS: NavLink[] = [
  { href: '/admin/dashboard', label: 'Dashboard', icon: 'dashboard' },
  { href: '/admin/executive', label: 'Executive Analytics', icon: 'dashboard' },
  { href: '/admin/companies', label: 'Companies', icon: 'company' },
  { href: '/admin/branches', label: 'Branches', icon: 'branch' },
  { href: '/admin/staff', label: 'Staff', icon: 'staff' },
  { href: '/admin/customers', label: 'Customers', icon: 'customer' },
  { href: '/admin/crm-dashboard', label: 'CRM Dashboard', icon: 'dashboard' },
  { href: '/admin/leads', label: 'Leads', icon: 'customer' },
  { href: '/admin/tasks', label: 'My Tasks', icon: 'shield' },
  { href: '/admin/support-tickets', label: 'Support Tickets', icon: 'bell' },
  { href: '/admin/flights', label: 'Flight Bookings', icon: 'flight' },
  { href: '/admin/flight-pricing-rules', label: 'Flight Pricing Rules', icon: 'flight' },
  { href: '/admin/flight-suppliers', label: 'Flight Suppliers', icon: 'flight' },
  { href: '/admin/flight-provider-routing', label: 'Flight Provider Routing', icon: 'flight' },
  { href: '/admin/suppliers', label: 'Suppliers', icon: 'company' },
  { href: '/admin/flight-service-fees', label: 'Flight Service Fees', icon: 'flight' },
  { href: '/admin/flight-reports', label: 'Flight Reports', icon: 'invoice' },
  { href: '/admin/hotels', label: 'Hotel Bookings', icon: 'hotel' },
  { href: '/admin/hotel-catalog', label: 'Hotel Catalog', icon: 'hotel' },
  { href: '/admin/hotel-reports', label: 'Hotel Reports', icon: 'invoice' },
  { href: '/admin/travel-packages', label: 'Travel Packages', icon: 'hotel' },
  { href: '/admin/vehicle-rentals', label: 'Vehicle Rentals', icon: 'car' },
  { href: '/admin/visa-operations', label: 'Visa Operations Center', icon: 'dashboard' },
  { href: '/admin/visa-applications', label: 'Visa Applications', icon: 'visa' },
  { href: '/admin/visa-country-rules', label: 'Country Visa Rules', icon: 'visa' },
  { href: '/admin/visa-services', label: 'Visa Services', icon: 'visa' },
  { href: '/admin/visa-incentives', label: 'Staff Incentives & Payouts', icon: 'wallet' },
  { href: '/admin/visa-reports', label: 'Visa Reports', icon: 'invoice' },
  { href: '/admin/corporate-travel', label: 'Corporate Travel', icon: 'corporate' },
  { href: '/admin/hajj-packages', label: 'Hajj Packages', icon: 'hajj' },
  { href: '/admin/umrah-packages', label: 'Umrah Packages', icon: 'umrah' },
  { href: '/admin/hajj-ops-dashboard', label: 'Hajj/Umrah Ops Center', icon: 'dashboard' },
  { href: '/admin/hajj-groups', label: 'Hajj Groups', icon: 'hajj' },
  { href: '/admin/umrah-groups', label: 'Umrah Groups', icon: 'umrah' },
  { href: '/admin/hajj-ops-fleet', label: 'Fleet & Transport', icon: 'car' },
  { href: '/admin/hajj-ops-checkin', label: 'Field Check-In', icon: 'shield' },
  { href: '/admin/invoices', label: 'Invoices', icon: 'invoice' },
  { href: '/admin/manual-payments', label: 'Manual Payments', icon: 'payment' },
  { href: '/admin/wallets', label: 'Wallets', icon: 'wallet' },
  { href: '/admin/finance-dashboard', label: 'Finance Dashboard', icon: 'invoice' },
  { href: '/admin/chart-of-accounts', label: 'Chart of Accounts', icon: 'invoice' },
  { href: '/admin/expenses', label: 'Expenses', icon: 'payment' },
  { href: '/admin/investments', label: 'Company Investment', icon: 'wallet' },
  { href: '/admin/supplier-payables', label: 'Supplier Payables', icon: 'payment' },
  { href: '/admin/daily-closing', label: 'Daily Closing', icon: 'invoice' },
  { href: '/admin/staff-bank-verification', label: 'Staff Bank Verification', icon: 'shield' },
  { href: '/admin/notifications', label: 'Notifications', icon: 'bell' },
  { href: '/admin/roles', label: 'Roles', icon: 'shield' },
  { href: '/admin/approvals', label: 'Approvals', icon: 'shield' },
  { href: '/admin/audit-log', label: 'Audit Log', icon: 'audit' },
  { href: '/admin/feature-flags', label: 'Feature Flags', icon: 'flag' },
  { href: '/admin/system-settings', label: 'System Settings', icon: 'gear' },
  { href: '/admin/api-keys', label: 'API Keys', icon: 'key' },
  { href: '/admin/data-export-import', label: 'Data Export & Import', icon: 'transfer' },
  { href: '/admin/backups', label: 'Backup Management', icon: 'backup' },
  { href: '/admin/ai-analytics', label: 'AI Analytics', icon: 'sparkle' },
  { href: '/admin/whatsapp', label: 'WhatsApp Inbox', icon: 'chat' },
  { href: '/admin/integrations', label: 'Integrations', icon: 'plug' },
  { href: '/admin/account', label: 'My Account', icon: 'account' },
];

/** Finance Officer lands on a narrower nav focused on invoicing/payments. */
const FINANCE_LINKS: NavLink[] = [
  { href: '/finance/dashboard', label: 'Dashboard', icon: 'dashboard' },
  { href: '/admin/executive', label: 'Executive Analytics', icon: 'dashboard' },
  { href: '/admin/finance-dashboard', label: 'Finance Dashboard', icon: 'invoice' },
  { href: '/admin/chart-of-accounts', label: 'Chart of Accounts', icon: 'invoice' },
  { href: '/admin/invoices', label: 'Invoices', icon: 'invoice' },
  { href: '/admin/manual-payments', label: 'Manual Payments', icon: 'payment' },
  { href: '/admin/expenses', label: 'Expenses', icon: 'payment' },
  { href: '/admin/supplier-payables', label: 'Supplier Payables', icon: 'payment' },
  { href: '/admin/daily-closing', label: 'Daily Closing', icon: 'invoice' },
  { href: '/admin/staff-bank-verification', label: 'Staff Bank Verification', icon: 'shield' },
  { href: '/admin/flight-reports', label: 'Flight Reports', icon: 'invoice' },
  { href: '/admin/hotel-reports', label: 'Hotel Reports', icon: 'invoice' },
  { href: '/admin/visa-incentives', label: 'Staff Incentives & Payouts', icon: 'wallet' },
  { href: '/admin/wallets', label: 'Wallets', icon: 'wallet' },
  { href: '/admin/notifications', label: 'Notifications', icon: 'bell' },
  { href: '/admin/api-keys', label: 'API Keys', icon: 'key' },
  { href: '/admin/account', label: 'My Account', icon: 'account' },
];

export const ADMIN_NAV: NavLink[] = assignGroups(ADMIN_LINKS, {
  'People & CRM': ['/admin/companies', '/admin/branches', '/admin/staff', '/admin/customers', '/admin/crm-dashboard', '/admin/leads', '/admin/tasks', '/admin/support-tickets'],
  'Flights': ['/admin/flights', '/admin/flight-pricing-rules', '/admin/flight-suppliers', '/admin/flight-provider-routing', '/admin/flight-service-fees', '/admin/flight-reports'],
  'Suppliers & Corporate': ['/admin/suppliers', '/admin/corporate-travel'],
  'Hotels & Rentals': ['/admin/hotels', '/admin/hotel-catalog', '/admin/hotel-reports', '/admin/travel-packages', '/admin/vehicle-rentals'],
  'Visa': ['/admin/visa-operations', '/admin/visa-applications', '/admin/visa-country-rules', '/admin/visa-services', '/admin/visa-incentives', '/admin/visa-reports'],
  'Hajj & Umrah': ['/admin/hajj-packages', '/admin/umrah-packages', '/admin/hajj-ops-dashboard', '/admin/hajj-groups', '/admin/umrah-groups', '/admin/hajj-ops-fleet', '/admin/hajj-ops-checkin'],
  'Finance': ['/admin/invoices', '/admin/manual-payments', '/admin/wallets', '/admin/finance-dashboard', '/admin/chart-of-accounts', '/admin/expenses', '/admin/investments', '/admin/supplier-payables', '/admin/daily-closing', '/admin/staff-bank-verification'],
  'System': ['/admin/notifications', '/admin/roles', '/admin/approvals', '/admin/audit-log', '/admin/feature-flags', '/admin/system-settings', '/admin/api-keys', '/admin/data-export-import', '/admin/backups', '/admin/ai-analytics', '/admin/whatsapp', '/admin/integrations'],
});

export const FINANCE_NAV: NavLink[] = assignGroups(FINANCE_LINKS, {
  'Money': ['/admin/finance-dashboard', '/admin/chart-of-accounts', '/admin/invoices', '/admin/manual-payments', '/admin/expenses', '/admin/supplier-payables', '/admin/daily-closing', '/admin/wallets'],
  'Reports & Payouts': ['/admin/flight-reports', '/admin/hotel-reports', '/admin/visa-incentives', '/admin/staff-bank-verification'],
  'Account': ['/admin/notifications', '/admin/api-keys', '/admin/account'],
});
