import type { NavLink } from '@/components/AppShell';

export const ADMIN_NAV: NavLink[] = [
  { href: '/admin/dashboard', label: 'Dashboard', icon: 'dashboard' },
  { href: '/admin/companies', label: 'Companies', icon: 'company' },
  { href: '/admin/branches', label: 'Branches', icon: 'branch' },
  { href: '/admin/staff', label: 'Staff', icon: 'staff' },
  { href: '/admin/customers', label: 'Customers', icon: 'customer' },
  { href: '/admin/crm-dashboard', label: 'CRM Dashboard', icon: 'dashboard' },
  { href: '/admin/leads', label: 'Leads', icon: 'customer' },
  { href: '/admin/tasks', label: 'My Tasks', icon: 'shield' },
  { href: '/admin/support-tickets', label: 'Support Tickets', icon: 'bell' },
  { href: '/admin/flights', label: 'Flight Bookings', icon: 'flight' },
  { href: '/admin/flight-pricing-rules', label: 'Flight Pricing Rules', icon: 'flight' },
  { href: '/admin/flight-reports', label: 'Flight Reports', icon: 'invoice' },
  { href: '/admin/hotels', label: 'Hotel Bookings', icon: 'hotel' },
  { href: '/admin/hotel-catalog', label: 'Hotel Catalog', icon: 'hotel' },
  { href: '/admin/hotel-reports', label: 'Hotel Reports', icon: 'invoice' },
  { href: '/admin/travel-packages', label: 'Travel Packages', icon: 'hotel' },
  { href: '/admin/vehicle-rentals', label: 'Vehicle Rentals', icon: 'car' },
  { href: '/admin/visa-applications', label: 'Visa Applications', icon: 'visa' },
  { href: '/admin/visa-services', label: 'Visa Services', icon: 'visa' },
  { href: '/admin/visa-incentives', label: 'Staff Incentives & Payouts', icon: 'wallet' },
  { href: '/admin/visa-reports', label: 'Visa Reports', icon: 'invoice' },
  { href: '/admin/corporate-travel', label: 'Corporate Travel', icon: 'corporate' },
  { href: '/admin/hajj-packages', label: 'Hajj Packages', icon: 'hajj' },
  { href: '/admin/umrah-packages', label: 'Umrah Packages', icon: 'umrah' },
  { href: '/admin/hajj-ops-dashboard', label: 'Hajj/Umrah Ops Center', icon: 'dashboard' },
  { href: '/admin/hajj-groups', label: 'Hajj Groups', icon: 'hajj' },
  { href: '/admin/umrah-groups', label: 'Umrah Groups', icon: 'umrah' },
  { href: '/admin/hajj-ops-fleet', label: 'Fleet & Transport', icon: 'car' },
  { href: '/admin/invoices', label: 'Invoices', icon: 'invoice' },
  { href: '/admin/manual-payments', label: 'Manual Payments', icon: 'payment' },
  { href: '/admin/wallets', label: 'Wallets', icon: 'wallet' },
  { href: '/admin/finance-dashboard', label: 'Finance Dashboard', icon: 'invoice' },
  { href: '/admin/chart-of-accounts', label: 'Chart of Accounts', icon: 'invoice' },
  { href: '/admin/expenses', label: 'Expenses', icon: 'payment' },
  { href: '/admin/investments', label: 'Company Investment', icon: 'wallet' },
  { href: '/admin/supplier-payables', label: 'Supplier Payables', icon: 'payment' },
  { href: '/admin/daily-closing', label: 'Daily Closing', icon: 'invoice' },
  { href: '/admin/staff-bank-verification', label: 'Staff Bank Verification', icon: 'shield' },
  { href: '/admin/notifications', label: 'Notifications', icon: 'bell' },
  { href: '/admin/roles', label: 'Roles', icon: 'shield' },
  { href: '/admin/integrations', label: 'Integrations', icon: 'plug' },
  { href: '/admin/account', label: 'My Account', icon: 'account' },
];

/** Finance Officer lands on a narrower nav focused on invoicing/payments. */
export const FINANCE_NAV: NavLink[] = [
  { href: '/finance/dashboard', label: 'Dashboard', icon: 'dashboard' },
  { href: '/admin/finance-dashboard', label: 'Finance Dashboard', icon: 'invoice' },
  { href: '/admin/chart-of-accounts', label: 'Chart of Accounts', icon: 'invoice' },
  { href: '/admin/invoices', label: 'Invoices', icon: 'invoice' },
  { href: '/admin/manual-payments', label: 'Manual Payments', icon: 'payment' },
  { href: '/admin/expenses', label: 'Expenses', icon: 'payment' },
  { href: '/admin/supplier-payables', label: 'Supplier Payables', icon: 'payment' },
  { href: '/admin/daily-closing', label: 'Daily Closing', icon: 'invoice' },
  { href: '/admin/staff-bank-verification', label: 'Staff Bank Verification', icon: 'shield' },
  { href: '/admin/flight-reports', label: 'Flight Reports', icon: 'invoice' },
  { href: '/admin/hotel-reports', label: 'Hotel Reports', icon: 'invoice' },
  { href: '/admin/visa-incentives', label: 'Staff Incentives & Payouts', icon: 'wallet' },
  { href: '/admin/wallets', label: 'Wallets', icon: 'wallet' },
  { href: '/admin/notifications', label: 'Notifications', icon: 'bell' },
  { href: '/admin/account', label: 'My Account', icon: 'account' },
];
